### ISSUE TITLE
Get content from bandcamp urls of the format https://{domain}.bandcamp.com/releases

### ISSUE THREAD

**Issue by geoff-maddock** [jamband/ripple#9]
As a user of ripple, I would like to be able to extract data from bandcamp URLs of formats that are not currently allowed by the regex:

For example the format:
https://{domain}.bandcamp.com/releases

Such as:
https://bravethesea.bandcamp.com/releases

Looks like an album and contains data in the header meta tags just like /album

**Comment by jamband** [comment]
Why would you want information from the `/releases` path? Is https://bravethesea.bandcamp.com/album/the-kraken no good?

**Comment by geoff-maddock** [comment]
https://github.com/jamband/ripple/issues/9#issuecomment-1247945733

I'm starting with just the base URL, which in this case, redirects from:
https://bravethesea.bandcamp.com/
to
[https://bravethesea.bandcamp.com/releases](https://bravethesea.bandcamp.com/releases)

I'd like to get the audio in the cases like that where I don't know the album.

**Comment by jamband** [comment]
@geoff-maddock  Added support for /releases in v0.11.0. Please update and check. However, you will not be able to retrieve data from https://bravethesea.bandcamp.com/ as we do not support redirects.

Please comment if you have any other problems. If not, please close this issue.

**Comment by geoff-maddock** [comment]
Excellent - thank you!
